/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as BoostsRouteImport } from './routes/boosts'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DrainsRouteImport } from './routes/drains'
import { Route as IdentityRouteImport } from './routes/identity'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as NextMoveRouteImport } from './routes/next-move'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as QuestsRouteImport } from './routes/quests'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QuestsIndexRouteImport } from './routes/quests.index'
import { Route as QuestsQuestIdRouteImport } from './routes/quests.$questId'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsAiRouteImport } from './routes/settings.ai'
import { Route as SettingsPrivacyRouteImport } from './routes/settings.privacy'
import { Route as SettingsStorageRouteImport } from './routes/settings.storage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const BoostsRoute = BoostsRouteImport.update({
  id: '/boosts',
  path: '/boosts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DrainsRoute = DrainsRouteImport.update({
  id: '/drains',
  path: '/drains',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityRoute = IdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const NextMoveRoute = NextMoveRouteImport.update({
  id: '/next-move',
  path: '/next-move',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsRoute = QuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsIndexRoute = QuestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuestsRoute,
} as any)
const QuestsQuestIdRoute = QuestsQuestIdRouteImport.update({
  id: '/$questId',
  path: '/$questId',
  getParentRoute: () => QuestsRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAiRoute = SettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsStorageRoute = SettingsStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/agent': typeof AgentRoute
  '/boosts': typeof BoostsRoute
  '/chat': typeof ChatRoute
  '/drains': typeof DrainsRoute
  '/identity': typeof IdentityRoute
  '/memory': typeof MemoryRoute
  '/next-move': typeof NextMoveRoute
  '/onboarding': typeof OnboardingRoute
  '/quests': typeof QuestsRouteWithChildren
  '/recovery': typeof RecoveryRoute
  '/settings': typeof SettingsRouteWithChildren
  '/quests/$questId': typeof QuestsQuestIdRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/quests/': typeof QuestsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/agent': typeof AgentRoute
  '/boosts': typeof BoostsRoute
  '/chat': typeof ChatRoute
  '/drains': typeof DrainsRoute
  '/identity': typeof IdentityRoute
  '/memory': typeof MemoryRoute
  '/next-move': typeof NextMoveRoute
  '/onboarding': typeof OnboardingRoute
  '/recovery': typeof RecoveryRoute
  '/quests/$questId': typeof QuestsQuestIdRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/quests': typeof QuestsIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/agent': typeof AgentRoute
  '/boosts': typeof BoostsRoute
  '/chat': typeof ChatRoute
  '/drains': typeof DrainsRoute
  '/identity': typeof IdentityRoute
  '/memory': typeof MemoryRoute
  '/next-move': typeof NextMoveRoute
  '/onboarding': typeof OnboardingRoute
  '/quests': typeof QuestsRouteWithChildren
  '/recovery': typeof RecoveryRoute
  '/settings': typeof SettingsRouteWithChildren
  '/quests/$questId': typeof QuestsQuestIdRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/quests/': typeof QuestsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisor'
    | '/agent'
    | '/boosts'
    | '/chat'
    | '/drains'
    | '/identity'
    | '/memory'
    | '/next-move'
    | '/onboarding'
    | '/quests'
    | '/recovery'
    | '/settings'
    | '/quests/$questId'
    | '/settings/ai'
    | '/settings/privacy'
    | '/settings/storage'
    | '/quests/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisor'
    | '/agent'
    | '/boosts'
    | '/chat'
    | '/drains'
    | '/identity'
    | '/memory'
    | '/next-move'
    | '/onboarding'
    | '/recovery'
    | '/quests/$questId'
    | '/settings/ai'
    | '/settings/privacy'
    | '/settings/storage'
    | '/quests'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/advisor'
    | '/agent'
    | '/boosts'
    | '/chat'
    | '/drains'
    | '/identity'
    | '/memory'
    | '/next-move'
    | '/onboarding'
    | '/quests'
    | '/recovery'
    | '/settings'
    | '/quests/$questId'
    | '/settings/ai'
    | '/settings/privacy'
    | '/settings/storage'
    | '/quests/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorRoute: typeof AdvisorRoute
  AgentRoute: typeof AgentRoute
  BoostsRoute: typeof BoostsRoute
  ChatRoute: typeof ChatRoute
  DrainsRoute: typeof DrainsRoute
  IdentityRoute: typeof IdentityRoute
  MemoryRoute: typeof MemoryRoute
  NextMoveRoute: typeof NextMoveRoute
  OnboardingRoute: typeof OnboardingRoute
  QuestsRoute: typeof QuestsRouteWithChildren
  RecoveryRoute: typeof RecoveryRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boosts': {
      id: '/boosts'
      path: '/boosts'
      fullPath: '/boosts'
      preLoaderRoute: typeof BoostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drains': {
      id: '/drains'
      path: '/drains'
      fullPath: '/drains'
      preLoaderRoute: typeof DrainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity': {
      id: '/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof IdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next-move': {
      id: '/next-move'
      path: '/next-move'
      fullPath: '/next-move'
      preLoaderRoute: typeof NextMoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests': {
      id: '/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof QuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/': {
      id: '/quests/'
      path: '/'
      fullPath: '/quests/'
      preLoaderRoute: typeof QuestsIndexRouteImport
      parentRoute: typeof QuestsRoute
    }
    '/quests/$questId': {
      id: '/quests/$questId'
      path: '/$questId'
      fullPath: '/quests/$questId'
      preLoaderRoute: typeof QuestsQuestIdRouteImport
      parentRoute: typeof QuestsRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/ai': {
      id: '/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof SettingsAiRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/storage': {
      id: '/settings/storage'
      path: '/storage'
      fullPath: '/settings/storage'
      preLoaderRoute: typeof SettingsStorageRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface QuestsRouteChildren {
  QuestsQuestIdRoute: typeof QuestsQuestIdRoute
  QuestsIndexRoute: typeof QuestsIndexRoute
}

const QuestsRouteChildren: QuestsRouteChildren = {
  QuestsQuestIdRoute: QuestsQuestIdRoute,
  QuestsIndexRoute: QuestsIndexRoute,
}

const QuestsRouteWithChildren =
  QuestsRoute._addFileChildren(QuestsRouteChildren)

interface SettingsRouteChildren {
  SettingsAiRoute: typeof SettingsAiRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsStorageRoute: typeof SettingsStorageRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAiRoute: SettingsAiRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsStorageRoute: SettingsStorageRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorRoute: AdvisorRoute,
  AgentRoute: AgentRoute,
  BoostsRoute: BoostsRoute,
  ChatRoute: ChatRoute,
  DrainsRoute: DrainsRoute,
  IdentityRoute: IdentityRoute,
  MemoryRoute: MemoryRoute,
  NextMoveRoute: NextMoveRoute,
  OnboardingRoute: OnboardingRoute,
  QuestsRoute: QuestsRouteWithChildren,
  RecoveryRoute: RecoveryRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
